### ISSUE TITLE
인텔리제이에서 모든 코드가 빨강 처리됨

### ISSUE THREAD

**Issue by orangecoppers** [Komtents/chasing-tails#3]
거의 모든 import들이 오류 처리되고 있습니다

**Comment by fi-xz** [comment]
새로 `git clone` 명령 이용 후 빌드 스크립트 Sync 진행 시 정상 처리되는것을 보아 재현이 불가능합니다.
본인의 빌드 환경을 확인하시길 바랍니다.

![image](https://github.com/user-attachments/assets/0a8ab77f-33f0-4523-a9ce-3244547ed0f3)

**Comment by fi-xz** [comment]
Can't reproduce

**Comment by fi-xz** [comment]
다음은 친절한 상기입니다:
![image](https://github.com/user-attachments/assets/fab4c7a2-c9e5-4d29-b0ee-dec93358c994)
