### ISSUE TITLE
꼬리잡기 나갔을떄 버그

### ISSUE THREAD

**Issue by teauk123** [Komtents/chasing-tails#4]
안녕하세요 꼬리잡기 즐기는 도중에 자꾸 애들이 튕기거나 그냥 나가버려서.. 다시 시작하려고 들어와도 시작이 안되고 계속 그자리에 멈춰 있고 어떻게 시작을 해도 모든 팀이 레드팀이 되면서 자기한테서 심장소리가 납니다 그래서 게임 멈추는 코드를 없애려했는데 힘드네요.. 어떻게 할까요?

**Comment by fi-xz** [comment]
# 다음은 친절한 상기입니다:
![image](https://github.com/user-attachments/assets/6541ea7e-7c4b-4a53-9f5a-e257e3c1db33)

**Comment by fi-xz** [comment]
현재 확인된 버그들을 차례로 수정하고 있습니다.

**Comment by fi-xz** [comment]
시간 소요가 어느정도 걸릴 것으로 예상됩니다. ETA는 없습니다.

**Comment by fi-xz** [comment]
fixed in cbd50c7

최신 릴리즈 패치 및 플러그인 설정 파일 삭제, 게임을 완전히 새로 시작 하신 후 동일 현상이 있다면 **버그 제보 조건에 맞춰서** 이슈를 생성하시길 바랍니다.
