### ISSUE TITLE
관전모드 플레이어가 1명+ 일때 게임 재시작 안됨.

### ISSUE THREAD

**Issue by chang235** [Komtents/chasing-tails#5]
관전모드 플레이어가 있을때 인게임 플레이어 한명이 나갔다 들어오면 게임 재시작이 안되는 버그가 있음.
(직접 테스트도 해보았음.)

**Comment by fi-xz** [comment]
.
![image](https://github.com/user-attachments/assets/f846b2c9-8874-407b-8078-64d786036f78)

**Comment by fi-xz** [comment]
b299311
