### ISSUE TITLE
[버그]한명만 팀 정해짐

### ISSUE THREAD

**Issue by Guni1231** [Komtents/chasing-tails#6]
### 발생한 문제 상황

시작을 하니 팀이 한명만 정해집니다

### 인 게임 로그

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2024-11-30 14:40:33
Description: Exception in server tick loop

java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_MAX_HEALTH'
	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.restoreDefaults(ChasingTailsGameManager.kt:142)
	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.stopGame(ChasingTailsGameManager.kt:125)
	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.commands.ChasingtailsCommand$registerCommand$1.run$lambda$4(ChasingtailsCommand.kt:101)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2241)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2215)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
```

### 인 게임 구동기/버전

paper 1.21.3

**Comment by Guni1231** [comment]
> ### 발생한 문제 상황
> 시작을 하니 팀이 한명만 정해집니다
> 
> ### 인 게임 로그
> ```shell
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 2024-11-30 14:40:33
> Description: Exception in server tick loop
> 
> java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_MAX_HEALTH'
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.restoreDefaults(ChasingTailsGameManager.kt:142)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.stopGame(ChasingTailsGameManager.kt:125)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.commands.ChasingtailsCommand$registerCommand$1.run$lambda$4(ChasingtailsCommand.kt:101)
> 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2241)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2215)
> 	at net.minecraft.server.TickTask.run(TickTask.java:18)
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554)
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547)
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
> 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498)
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508)
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344)
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ```
> 
> ### 인 게임 구동기/버전
> paper 1.21.3

**Comment by Guni1231** [comment]
> ### 발생한 문제 상황
> 시작을 하니 팀이 한명만 정해집니다
> 
> ### 인 게임 로그
> ```shell
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 2024-11-30 14:40:33
> Description: Exception in server tick loop
> 
> java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_MAX_HEALTH'
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.restoreDefaults(ChasingTailsGameManager.kt:142)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.stopGame(ChasingTailsGameManager.kt:125)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.commands.ChasingtailsCommand$registerCommand$1.run$lambda$4(ChasingtailsCommand.kt:101)
> 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2241)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2215)
> 	at net.minecraft.server.TickTask.run(TickTask.java:18)
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554)
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547)
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
> 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498)
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508)
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344)
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ```
> 
> ### 인 게임 구동기/버전
> paper 1.21.3

**Comment by Guni1231** [comment]
> ### 발생한 문제 상황
> 시작을 하니 팀이 한명만 정해집니다
> 
> ### 인 게임 로그
> ```shell
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 2024-11-30 14:40:33
> Description: Exception in server tick loop
> 
> java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_MAX_HEALTH'
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.restoreDefaults(ChasingTailsGameManager.kt:142)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.managers.ChasingTailsGameManager.stopGame(ChasingTailsGameManager.kt:125)
> 	at chasing-tails (1).jar//me.prdis.chasingtails.plugin.commands.ChasingtailsCommand$registerCommand$1.run$lambda$4(ChasingtailsCommand.kt:101)
> 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2241)
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2215)
> 	at net.minecraft.server.TickTask.run(TickTask.java:18)
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577)
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554)
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547)
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
> 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498)
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508)
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344)
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ```
> 
> ### 인 게임 구동기/버전
> paper 1.21.3

**Comment by fi-xz** [comment]
최신 버전의 플러그인을 다운 받고 실행해주시길 바랍니다.
